config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :products
  root 'products#index'

  resource :cart do
    post 'add', path: 'add/:id'
    get 'checkout'
  end

  resources :orders, except: [:edit, :update, :destroy]

  namespace :backend do
    get 'dashboard', to:'dashboard#index'
    resources :products, except:[:show]
    resources :categories, except:[:show]
    resources :orders, except: [:destroy] do
      post 'pay'
      post 'out'
      post 'deliver'
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items

  validates :name, presence: true
  validates :tel, presence: true
  validates :address, presence: true

  state_machine :initial => :pending do
    event :pay do
      transition :pending => :paid
    end

    event :out do
      transition :paid => :out
    end

    event :deliver do
      transition :out => :delivered
    end
  end

end

app/controllers/backend/base_controller.rb
class Backend::BaseController < ApplicationController
  layout 'backend'

  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/backend/categories_controller.rb
class Backend::CategoriesController < Backend::BaseController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to backend_categories_path
    else
      render :new
    end
  end

  def edit
    # TODO
  end

  def update
    # TODO
  end

  def destroy
    # TODO
  end

  def category_params
    params.require(:category).permit(:name, :category_id)
  end
end

app/controllers/backend/dashboard_controller.rb
class Backend::DashboardController < Backend::BaseController
  def index
    authorize! :manage, :all
  end
end

app/controllers/backend/orders_controller.rb
class Backend::OrdersController < Backend::BaseController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find_by(id: params[:id])
  end

  def pay
    @order = Order.find(params[:order_id])
    if @order.pay
      # sending email
      redirect_to :back, notice:'狀態變更成已付款'
    else
      redirect_to :back, alert:'狀態錯誤'
    end
  end

  def out
    @order = Order.find(params[:order_id])
    if @order.out
      # sending email
      redirect_to :back, notice:'狀態變更成已出貨'
    else
      redirect_to :back, alert:'狀態錯誤'
    end
  end

  def deliver
    @order = Order.find(params[:order_id])
    if @order.deliver
      # sending email
      redirect_to :back, notice:'狀態變更成已到貨'
    else
      redirect_to :back, alert:'狀態錯誤'
    end
  end
end

app/controllers/backend/products_controller.rb
class Backend::ProductsController < Backend::BaseController
  before_action :find_product, only:[:edit, :update, :destroy]

  def index
    @products = Product.page(params[:page]).per(10)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to backend_products_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to backend_products_path, notice: '成功更新商品'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to backend_products_path
  end

  private
  def find_product
    @product = Product.find_by(id: params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :is_online, :image)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :initialize_cart

  def create
    @order = Order.new(order_params)
    @cart.items.each do |item|
      @order.order_items.build(product: item.product, quantity: item.quantity)
    end

    if @order.save
      # 進行交易
      Braintree::Transaction.sale(
        :amount => @cart.total_price,
        :payment_method_nonce => "nonce-from-the-client"
      )

      # 清除購物車
      session['cart'] = nil

      redirect_to root_path, notice:'感謝您!'
    else
      # TODO
    end
  end

  private
  def order_params
    params.require(:order).permit(:name, :tel, :address, :will_receive_email)
  end
end

app/helpers/backend/base_helper.rb
module Backend::BaseHelper
  def edit_button(path)
    link_to '編輯', path, class:'btn btn-success btn-xs'
  end

  def delete_button(path)
    link_to '刪除', path, method: :delete, class:'btn btn-danger btn-xs', data:{confirm:'確定嗎?'}
  end
end

app/helpers/backend/orders_helper.rb
module Backend::OrdersHelper
  def state_tag(order)

    case order.state
    when 'pending'
      content_tag :span, class:'text-danger' do
        "未處理"
      end
    when 'paid'
      content_tag :span, class:'text-info' do
        "已付款"
      end
    when 'out'
      content_tag :span, class:'text-success' do
        "已出貨"
      end
    when 'delivered'
        content_tag :span, class:'text-primary' do
        "已到貨"
      end
    end
  end
end

app/helpers/backend/products_helper.rb
module Backend::ProductsHelper
  def product_status(product)
    if product.is_online
      "是"
    else
      "否"
    end
  end
end

app/views/backend/orders/_state_buttons.html.erb
<% if order.state == 'pending' %>
  <%= link_to '付費', backend_order_pay_path(order), method: :post, class:'btn btn-xs btn-primary'%>
<% elsif order.state == 'paid' %>
    <%= link_to '出貨', backend_order_out_path(order), method: :post, class:'btn btn-xs btn-primary' %>
<% elsif order.state == 'out' %>
    <%= link_to '到貨', backend_order_deliver_path(order), method: :post, class:'btn btn-xs btn-primary' %>
<% end %>

app/views/backend/orders/index.html.erb
<h1>訂單列表</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <td>訂單編號</td>
      <td>收件人</td>
      <td>電話</td>
      <td>地址</td>
      <td>狀態</td>
      <td>處理</td>
    </tr>
  </thead>
  <% @orders.each do |order| %>
    <tr>
      <td><%= order.id %></td>
      <td><%= link_to order.name, backend_order_path(order) %></td>
      <td><%= order.tel %></td>
      <td><%= order.address %></td>
      <td><%= state_tag(order) %></td>
      <td>
        <%= render 'state_buttons', order: order %>
      </td>
    </tr>
  <% end %>
</table>

app/views/backend/orders/show.html.erb
<h1>訂單資訊</h1>

姓名：<%= @order.name %><br />
電話：<%= @order.tel %><br />
地址：<%= @order.address %><br />
狀態：<%= state_tag(@order) %><br />

<h3>內容</h3>
<table class="table">
  <thead>
    <tr>
      <td>品項</td>
      <td>數量</td>
      <td>價錢</td>
    </tr>
  </thead>
<% @order.order_items.each do |item| %>
    <tr>
      <td><%= item.product.name %></td>
      <td><%= item.quantity %></td>
      <td>價錢</td>
    </tr>
<% end %>
</ul>