config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :products
  root 'products#index'

  resource :cart do
    post 'add', path: 'add/:id'
    get 'checkout'
  end

  resources :orders, except: [:edit, :update, :destroy]

  namespace :backend do
    get 'dashboard', to:'dashboard#index'
    resources :products, except:[:show]
    resources :categories, except:[:show]
    resources :orders, except: [:destroy] do
      post 'pay'
      post 'out'
      post 'deliver'
    end
  end
end

app/models/cart.rb
class Cart
  attr_reader :items

  def self.build_from_hash(hash)

    if hash.nil?
      items = []
    else
      items = hash["cart"]["items"].map do |item|
        CartItem.new(item["product_id"], item["quantity"])
      end
    end

    Cart.new(items)
  end

  def initialize(items = [])
    @items = items
  end

  def add_item(product_id)
    item = @items.find { |item| item.product_id == product_id }

    if item
      item.increment
    else
      @items << CartItem.new(product_id)
    end
  end

  def empty?
    @items.empty?
  end

  def serialize
    items = @items.map do |item|
      {"product_id" => item.product_id, "quantity" => item.quantity}
    end

    {
      "cart" => {
        "items" => items
      }
    }
  end

  def total_price
    total = items.inject(0) { |sum, item| sum + item.price }
    if total >= 1000
      total = total - 100
    else
      total
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :initialize_cart

  def add
    product = Product.find_by(id: params[:id])
    if product
      @cart.add_item(product.id)
      session[:cart] = @cart.serialize
      redirect_to :back, notice: "#{product.name} 已成功加入購物車"
    else
      redirect_to :back, notice: "無此商品"
    end
  end

  def show
  end

  def checkout
    @order = Order.new
    @token = Braintree::ClientToken.generate
  end

end

app/views/carts/_mycart.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <td>項目</td>
      <td>數量</td>
      <td>價錢</td>
    </tr>
  </thead>
  <% cart.items.each do |item| %>
  <tbody>
    <tr>
      <td><%= link_to item.product.name, product_path(item.product) %></td>
      <td><%= item.quantity %></td>
      <td><%= number_to_currency item.price %></td>
    </tr>
  </tbody>
  <% end %>
  <tfoot>
    <tr>
      <td colspan="2">總計</td>
      <td><%= number_to_currency cart.total_price %></td>
    </tr>
  </tfoot>
</table>

app/views/carts/checkout.html.erb
<% content_for :js do %>
<script src="https://js.braintreegateway.com/v2/braintree.js"></script>
<% end %>

<h1>結帳</h1>

<%= render 'mycart', cart: @cart %>

<hr/>

<h3>收件人</h3>
<%= simple_form_for @order do |f| %>
  <%= f.input :name, label: false, placeholder:'收件者姓名' %>
  <%= f.input :tel, label: false, placeholder:'電話' %>
  <%= f.input :address, label: false, placeholder:'地址' %>
  <%= f.input :will_receive_email %>
  <hr />
  <div id="dropin"></div>

  <hr />
  <%= f.submit '確認下訂' %>
  <hr />
<% end %>

<script>
braintree.setup(
  "<%= @token %>",
  'dropin', {
    container: 'dropin'
  });
</script>

app/views/carts/show.html.erb
<h1>購物車</h1>

<%= render 'mycart', cart: @cart %>

<%= link_to '繼續選購', products_path, class:'btn btn-primary' %>
<%= link_to '結帳', checkout_cart_path, class:'btn btn-danger' if @cart.total_price > 0 %>