config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :products
  root 'products#index'

  resource :cart do
    post 'add', path: 'add/:id'
    get 'checkout'
  end

  resources :orders, except: [:edit, :update, :destroy]

  namespace :backend do
    get 'dashboard', to:'dashboard#index'
    resources :products, except:[:show]
    resources :categories, except:[:show]
    resources :orders, except: [:destroy] do
      post 'pay'
      post 'out'
      post 'deliver'
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  # mount_uploader :image, ProductImageUploader
  belongs_to :category
end

app/controllers/backend/base_controller.rb
class Backend::BaseController < ApplicationController
  layout 'backend'

  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/backend/categories_controller.rb
class Backend::CategoriesController < Backend::BaseController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to backend_categories_path
    else
      render :new
    end
  end

  def edit
    # TODO
  end

  def update
    # TODO
  end

  def destroy
    # TODO
  end

  def category_params
    params.require(:category).permit(:name, :category_id)
  end
end

app/controllers/backend/dashboard_controller.rb
class Backend::DashboardController < Backend::BaseController
  def index
    authorize! :manage, :all
  end
end

app/controllers/backend/orders_controller.rb
class Backend::OrdersController < Backend::BaseController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find_by(id: params[:id])
  end

  def pay
    @order = Order.find(params[:order_id])
    if @order.pay
      # sending email
      redirect_to :back, notice:'狀態變更成已付款'
    else
      redirect_to :back, alert:'狀態錯誤'
    end
  end

  def out
    @order = Order.find(params[:order_id])
    if @order.out
      # sending email
      redirect_to :back, notice:'狀態變更成已出貨'
    else
      redirect_to :back, alert:'狀態錯誤'
    end
  end

  def deliver
    @order = Order.find(params[:order_id])
    if @order.deliver
      # sending email
      redirect_to :back, notice:'狀態變更成已到貨'
    else
      redirect_to :back, alert:'狀態錯誤'
    end
  end
end

app/controllers/backend/products_controller.rb
class Backend::ProductsController < Backend::BaseController
  before_action :find_product, only:[:edit, :update, :destroy]

  def index
    @products = Product.page(params[:page]).per(10)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to backend_products_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to backend_products_path, notice: '成功更新商品'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to backend_products_path
  end

  private
  def find_product
    @product = Product.find_by(id: params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :is_online, :image)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :initialize_cart

  def index
    @products = Product.all
  end

  def show
    @product = Product.find_by(id: params[:id])
  end

end

app/helpers/backend/base_helper.rb
module Backend::BaseHelper
  def edit_button(path)
    link_to '編輯', path, class:'btn btn-success btn-xs'
  end

  def delete_button(path)
    link_to '刪除', path, method: :delete, class:'btn btn-danger btn-xs', data:{confirm:'確定嗎?'}
  end
end

app/helpers/backend/orders_helper.rb
module Backend::OrdersHelper
  def state_tag(order)

    case order.state
    when 'pending'
      content_tag :span, class:'text-danger' do
        "未處理"
      end
    when 'paid'
      content_tag :span, class:'text-info' do
        "已付款"
      end
    when 'out'
      content_tag :span, class:'text-success' do
        "已出貨"
      end
    when 'delivered'
        content_tag :span, class:'text-primary' do
        "已到貨"
      end
    end
  end
end

app/helpers/backend/products_helper.rb
module Backend::ProductsHelper
  def product_status(product)
    if product.is_online
      "是"
    else
      "否"
    end
  end
end

app/views/backend/products/_form.html.erb
<%= simple_form_for [:backend, @product] do |f| %>
  <%= f.input :name %>
  <%= f.association :category %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :is_online %>
  <%= f.input :image, as: :file %>
  <%= f.submit %>
<% end %>

app/views/backend/products/edit.html.erb
<h1>更新商品</h1>
<%= render 'form' %>

app/views/backend/products/index.html.erb
<h1>商品列表</h1>

<%= link_to '新增', new_backend_product_path, class:'btn btn-success' %>

<table class="table table-hover">
  <thead>
    <tr>
      <td>商品名稱</td>
      <td>商品圖片</td>
      <td>售價</td>
      <td>是否上線</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= image_tag(product.image.small) %></td>
      <td><%= product.price %></td>
      <td><%= product_status(product) %></td>
        <td>
          <%= edit_button(edit_backend_product_path(product)) %>
          <%= delete_button(backend_product_path(product)) %>
        </td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @products, theme: 'twitter-bootstrap-3' %>

app/views/backend/products/new.html.erb
<h1>新增商品</h1>
<%= render 'form' %>