config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :products
  root 'products#index'

  resource :cart do
    post 'add', path: 'add/:id'
    get 'checkout'
  end

  resources :orders, except: [:edit, :update, :destroy]

  namespace :backend do
    get 'dashboard', to:'dashboard#index'
    resources :products, except:[:show]
    resources :categories, except:[:show]
    resources :orders, except: [:destroy] do
      post 'pay'
      post 'out'
      post 'deliver'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def initialize_cart
    @cart = Cart.build_from_hash(session[:cart])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_cart.html.erb
<%= link_to cart_path do %>
  購物車
  <% if @cart && !@cart.empty? %>
    <span class="badge"><%= @cart.items.length %></span>
  <% end %>
<% end %>

app/views/application/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= message %>
</div>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Barbrothers</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to '商品列表', products_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= render 'cart'%></li>

        <% if user_signed_in? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to '更新個人資料', edit_user_registration_path %></li>

              <% if can? :manage, User %>
              <li><%= link_to '後台管理系統', backend_dashboard_path %></li>
              <% end %>

              <li class="divider"></li>
              <li><%= link_to '登出', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to '註冊', new_user_registration_path %></li>
          <li><%= link_to '登入', backend_dashboard_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/application/_navbar_backend.html.erb
<%#TODO:把 product & category 連結加至選單中%>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">商店管理系統</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to '商品分類', backend_categories_path %></li>
        <li><%= link_to '商品列表', backend_products_path %></li>
        <li><%= link_to '訂單查詢', backend_orders_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to '更新個人資料', edit_user_registration_path %></li>
              <% if can? :manage, User %>
              <li><%= link_to '後台管理系統', backend_dashboard_path %></li>
              <% end %>
              <li class="divider"></li>
              <li><%= link_to '登出', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to '註冊', new_user_registration_path %></li>
          <li><%= link_to '登入', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>